### ISSUE TITLE
buttons not working on ESP32

### ISSUE THREAD

**Issue by Stef-aap** [gavinlyonsrepo/TM1638plus#1]
when I compile standard for the ESP32, display seems to work well, but only button 1 is detected. For this test I use the example TM1638plus_Test.
It seems to be some problem with the CPU frequency, because
standard cpu = 240 MHz, only button 1
compile for cpu = 80 MHz, button 1,2,3,4 are detected, button 6 sometimes

**Comment by gavinlyonsrepo** [comment]
See issue 2
