### ISSUE TITLE
High speed buttons error

### ISSUE THREAD

**Issue by IntrCol** [gavinlyonsrepo/TM1638plus#16]
The first button press cannot be detected when using high speed devices.
Fixed by moving last delayMicroseconds(1); to start of for loop in
TM1638plus_common::HighFreqshiftin

PS: the TM1638 works fine on 3.3V no need for voltage level shift

**Comment by gavinlyonsrepo** [comment]
Hi 

thanks for feedback.

Ya, i mentioned that in the readme in _**Note B : High frequency micro-controllers.**_
Someone mentioned that before in a email IIRC although I have never seen it. 
Which device are you using and at what frequency is the anomaly  ?

regards

**Comment by IntrCol** [comment]
Hello
I am using an ESP32 running at 240MHz, the buttons are read correctly in
the setup part of the program but not in the loop when lots of updates are
written even after a delay.
I changed the method to the following and everything reads fine now.
All display functions work fine

uint8_t  TM1638plus_common::HighFreqshiftin(uint8_t dataPin, uint8_t
clockPin, uint8_t bitOrder)
{
    uint8_t value = 0;
    uint8_t i = 0;

    for(i = 0; i < 8; ++i) {
        delayMicroseconds(1);
        if(bitOrder == LSBFIRST)
            value |= digitalRead(dataPin) << i;
        else
            value |= digitalRead(dataPin) << (7 - i);

        digitalWrite(clockPin, HIGH);
        delayMicroseconds(1);
        digitalWrite(clockPin, LOW);
    }
    return value;
}

**Comment by gavinlyonsrepo** [comment]
Hi 

I created a new version "1.8.0" minor update. To make the function more like  arduino core one in wiring_shift.c
https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/wiring_shift.c

You can test it if you want and report back please see if it works, it should. 

regards

**Comment by IntrCol** [comment]
Thank you, I will test over the weekend and get back to you with the
results.

**Comment by IntrCol** [comment]
Good day

I tested the version 1.8.0 and it is working perfectly, thank you very much
for your help.
