### ISSUE TITLE
not working on ESP32, answer

### ISSUE THREAD

**Issue by Stef-aap** [gavinlyonsrepo/TM1638plus#2]
sorry I don't know how to react on an issue, but I found a working solution (the main problem is the function shiftIn which shoudl be delayed)

**uint8_t shiftInX(uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder) {**
    uint8_t value = 0;
    uint8_t i;

    for(i = 0; i < 8; ++i) {
        //digitalWrite(clockPin, HIGH);
        if(bitOrder == LSBFIRST)
            value |= digitalRead(dataPin) << i;
        else
            value |= digitalRead(dataPin) << (7 - i);
        digitalWrite(clockPin, HIGH);
**delayMicroseconds(1);**
        digitalWrite(clockPin, LOW);
**delayMicroseconds(1);**
    }
//Serial.println ( "*********************");
    return value;
}

uint8_t TM1638plus::readButtons()
{
  uint8_t buttons = 0;
**digitalWrite(_CLOCK_IO, LOW);  //SM**
  digitalWrite(_STROBE_IO, LOW);
**delayMicroseconds(1);**
  shiftOut(_DATA_IO, _CLOCK_IO, LSBFIRST, BUTTONS_MODE);
  pinMode(_DATA_IO, INPUT);
  
  for (uint8_t i = 0; i < 4; i++)
  {
    uint8_t v = **shiftInX**(_DATA_IO, _CLOCK_IO, LSBFIRST) << i;
    buttons |= v;
  }

  pinMode(_DATA_IO, OUTPUT);
  digitalWrite(_STROBE_IO, HIGH); 
  return buttons;
}

**Comment by gavinlyonsrepo** [comment]
Hi 

Thanks for feedback

This library was only tested on arduino UNO and NANO.
I don't currently possess a ESP32.

Do you know how to do pull request?
Can you send in your working code change via pull request and I will review it.

Regards

**Comment by gavinlyonsrepo** [comment]
Hi 

I just tested it on a ESP-12E ESP8266 NodeMCU module at both 80MHZ and 160 MHZ.
The Button Function works once it is delayed or debouched , i.e not polled continuously.
on Both model 1 and 2. I still have not acquired a ESP32 module.

**Comment by gavinlyonsrepo** [comment]
Hi 

The program will now work with ESP32 at 240Mhz as of version 1.6.0
