### ISSUE TITLE
Communication with TM1638 randomly broken.

### ISSUE THREAD

**Issue by PavelTesar** [gavinlyonsrepo/TM1638plus#20]
I have a problem with the communication between arduino mega and TM1638 model1 breaking down. Only a new initialization of the TM1638 will help. I assume it's some kind of interference. Do you know where the problem could be?

**Comment by gavinlyonsrepo** [comment]
Hi 

I doubt its the TM1638plus software library , you can verify this by trying a different library.

What else is in circuit?
What are you using for a PSU? 
Is everything in circuit grounded?
What is your code?

Regards

**Comment by PavelTesar** [comment]
Hi,

In circuit
https://dratek.cz/arduino/879-arduino-rele-modul-8-kanalu-s-optickym-oddelenim.html
2x https://dratek.cz/arduino/1756-izolacni-modul-s-optocleny-4-kanalovy-pc817.html 
https://dratek.cz/arduino/51402-izolacni-modul-s-optocleny-3-kanalovy-ac-220v.html

PSU is PC AT power source.

Everything is grounded and very carefully.

I can try another library, but the code is 2000 lines long. I chose the library because it had good references.

**Comment by gavinlyonsrepo** [comment]
Hi 

I have a clock project with this library(TM1638plus) that works for days updating every second 
with no problems. 

How often do you update the display? 
When it "communication breaking down" What happens on display?
When you "a new initialization" Do you issue displayBegin() or just reset() or toggle Power to restore display
Are you using 3.3V or 5V PSU?
What data do you send? 

regards

**Comment by PavelTesar** [comment]
Hi,

The update is done randomly, sometimes it can take several tens of minutes.
When communication is interrupted, random content appears on the display (spontaneously).
The new initialisation is meant to be "displayBegin()" or other command is not work.
PSU is 5V,

I don't really understand the last question.

**Comment by gavinlyonsrepo** [comment]
Hi

I was just looking at datasheet there.

(1) Vcc filter capacitors
These modules usually have two filter capacitors between VCC and GND
Are these present and correct on your module?
You can try adding an extra filter capacitor on VCC.


(2)
In addition It recommends 3 more capacitors on the data lines.
These are not usually present.
"The three 100pF capacitors connected to the DIO, CLK, STB communication port
can reduce the interference of the communication port."
You can try adding these  3 capacitors. 

![4se](https://user-images.githubusercontent.com/21970139/187033228-6089ef59-51a5-47e3-a01b-8626d901579d.png)

**Comment by PavelTesar** [comment]
Hi,

Thank you for your reply.
I tried the recommendation from the chip manufacturer. Unfortunately, adding 100pF to the data pins made the whole situation even worse. I tested all possible combinations (only data, only power, all pin).

Best regards

**Comment by centic9** [comment]
I just recently had a case where one module did not work reliably. I had ordered two and when I tried the other one it worked fine and I use it a lot since then without any problem. 

So it is possible that you encounter some hardware issue, maybe also caused by how you connect it, but it may simply be broken.

**Comment by PavelTesar** [comment]
Hi,

I changed everything. The module, the cables. And that was before I wrote to you. But thank you for trying to help.

Best regards

**Comment by gavinlyonsrepo** [comment]
Problem is project related not library related , most likely.
