### ISSUE TITLE
Support for LKM variant (the 8x bicolor LED variant)

### ISSUE THREAD

**Issue by vertex-github** [gavinlyonsrepo/TM1638plus#8]
Could you add support for the bicolor LED variant board (LKM1638 I believe)

**Comment by gavinlyonsrepo** [comment]
HI 

I will ,  It will take a few weeks as I don't have that board.

Regards

**Comment by gavinlyonsrepo** [comment]
Hi 

I have just released a new version 1.6.0 please update when it is available in arduino library manager,
and you can test your board with model3 example file.

I got the board and tested/updated the library and added new function setLEDs in addition to setLED
The board I got was labelled Tm1638 v1.3 
I have seen various versions on-line 

1. LKM1638 v1.1
2. LKM1638 v1.2
3. TM1638 V1.3 

I think the differences are just related to board layout, connectors and some passive components, I assume from a software point of view they are the same.

Regards
